dependencies:
  - name: nginx-ingress
    version: 0.23.0
    repository: "alias:stable"
  - name: prometheus-operator
    version: 0.0.29
    repository: "alias:coreos"
  - name: kube-prometheus
    version: 0.0.105
    repository: "alias:coreos"