global:
  image:
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      #nginx.ingress.kubernetes.io/rewrite-target: /api/shifts
    # kubernetes.io/tls-acme: "true"
    host: shiftscheduler.netlify.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  httpPort: 8080