apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: {{ template "shift-scheduler.fullname" . }}
  labels:
    prometheus: kube-prometheus
spec:
  namespaceSelector:
    matchNames: 
      - default
  selector:
    matchLabels:
      app: {{ template "shift-scheduler.name" . }}
  endpoints:
    - metricRelabelings: 
      - sourceLabels: [__name__]
        targetLabel: __name__
        replacement: shifts_scheduler_${1}