apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "shift-scheduler.fullname" . }}
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: {{ template "shift-scheduler.name" . }}
  endpoints:
    - metricRelabelings: 
      - sourceLabels: [__name__]
        targetLabel: __name__
        replacement: shifts_scheduler_${1}
