# Default values for installation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 2
  image:
    repository: iluvzhouying/shift-scheduler-app
  serverPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  # kubernetes.io/tls-acme: "true"
  host: chart-example.local
  paths:
    - /employee/1/shifts # ^\/(?!api\/)\S*
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
