{{- if .Values.enabled -}}
{{- $fullName := include "shift-scheduler.fullname" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "shift-scheduler.name" . }}
    chart: {{ template "shift-scheduler.chart" . }}
    release: {{ $releaseName }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.tls }}
  tls:
  {{- range .Values.tls }}
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        {{- range .Values.paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ printf "%s-%s" $releaseName .service }}
              servicePort: {{ .port }}
        {{- end }}
{{- end }}
