#!/bin/bash

set -euxo pipefail

helm_version=2.11.0

# install gcloud
curl -o /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz
tar -xzf /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz -C /tmp/
/tmp/google-cloud-sdk/install.sh -q

# install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

# install helm
curl -o /tmp/helm-v${helm_version}-linux-amd64.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v${helm_version}-linux-amd64.tar.gz
tar -xzf /tmp/helm-v${helm_version}-linux-amd64.tar.gz -C /tmp/
sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm