#!/bin/bash

set -euxo pipefail

# install gcloud
curl -o /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz
tar -xzf /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz -C /tmp/
/tmp/google-cloud-sdk/install.sh -q

# install kubectl
gcloud components install kubectl

# install helm
curl -o /tmp/helm-v2.9.1-linux-amd64.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz
tar -xzf /tmp/helm-v2.9.1-linux-amd64.tar.gz -C /tmp/
sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm