#!/bin/bash

set -euxo pipefail

gcloud auth activate-service-account --key-file=ci-deploy-key.json

project_id="$(gcloud projects list --format="csv[no-heading](PROJECT_ID)")"
cluster="$(gcloud container clusters list --project ${project_id} --format="csv[no-heading](NAME,LOCATION)")"
cluster_name="$(echo "${cluster}" | cut -d ',' -f 1-1)"
# Weird travis ci bug related to the word "LOCATION" does not let cluster zone show up,
# so right now the workaround is to hardcode the zone into an env variable on the travis ci servers. 
# CLUSTER_ZONE="$(echo "${cluster}" | cut -d ',' -f 2-2)"
reserved_ip="$(gcloud compute addresses list --project ${project_id} --format="csv[no-heading](ADDRESS)")"

gcloud container clusters get-credentials "${cluster_name}" --zone "${CLUSTER_ZONE}" --project "${project_id}"

SHIFTS_IMAGE_TAG=$(curl -s https://hub.docker.com/v2/repositories/iluvzhouying/shift-scheduler-shifts/tags/?page_size=1 | jq -r '.results|.[0]|.name')
ADMIN_IMAGE_TAG=$(curl -s https://hub.docker.com/v2/repositories/iluvzhouying/shift-scheduler-admin/tags/?page_size=1 | jq -r '.results|.[0]|.name')

helm init --client-only
helm dependency update
chart_pkg_name="$(helm package --version 0.0.$(git rev-list --count master) . | grep  -Po '(?<=\/)[a-z-]+-0\.0\.\d+\.tgz')"
helm upgrade --install shift-scheduler ./"${chart_pkg_name}" --set \
    shifts.deployment.image.tag="${SHIFTS_IMAGE_TAG}",admin.deployment.image.tag="${ADMIN_IMAGE_TAG}",nginx-ingress.controller.service.loadBalancerIP="${reserved_ip}"
    