#!/bin/bash

set -euxo pipefail

gcloud auth activate-service-account --key-file=ci-deploy-key.json

project_id="$(gcloud projects list --format="csv[no-heading](PROJECT_ID)")"
cluster="$(gcloud container clusters list --project ${project_id} --format="csv[no-heading](NAME,LOCATION)")"
cluster_name="$(echo "${cluster}" | cut -d ',' -f 1-1)"
# Weird travis ci bug related to the word "LOCATION" does not let cluster zone show up,
# so right now the workaround is to hardcode the zone into an env variable on the travis ci servers. 
# CLUSTER_ZONE="$(echo "${cluster}" | cut -d ',' -f 2-2)"
reserved_ip="$(gcloud compute addresses list --project ${project_id} --format="csv[no-heading](ADDRESS)")"

gcloud container clusters get-credentials "${cluster_name}" --zone "${CLUSTER_ZONE}" --project "${project_id}"

helm init --client-only

helm upgrade nginx-ingress stable/nginx-ingress --install --namespace ingress --set controller.service.loadBalancerIP="${reserved_ip}"

helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm upgrade prometheus-operator coreos/prometheus-operator --install --namespace monitoring
helm upgrade kube-prometheus coreos/kube-prometheus --install --namespace monitoring \
    --set prometheus.serviceMonitorNamespaceSelector.matchNames={default} \
    --set prometheus.ruleNamespaceSelector.matchNames={default} \
    --set prometheus.externalLabels.cluster=${cluster_name} \
    --set alertmanager.configFromSecret=alertmanager-kube-prometheus \
    --set grafana.serverDashboardConfigmaps={shift-scheduler-dashboards} \
    --set exporter-kubelets.https=false \
    --set deployKubeControllerManager=false \
    --set deployKubeScheduler=false
  

SHIFTS_IMAGE_TAG=$(curl -s https://hub.docker.com/v2/repositories/iluvzhouying/shift-scheduler-shifts/tags/?page_size=1 | jq -r '.results|.[0]|.name')
ADMIN_IMAGE_TAG=$(curl -s https://hub.docker.com/v2/repositories/iluvzhouying/shift-scheduler-admin/tags/?page_size=1 | jq -r '.results|.[0]|.name')
chart_pkg_name="$(helm package --version 0.0.$(git rev-list --count master) . | grep  -Po '(?<=\/)[a-z-]+-0\.0\.\d+\.tgz')"
helm upgrade shift-scheduler ./"${chart_pkg_name}" --install \
    --set shifts.deployment.image.tag="${SHIFTS_IMAGE_TAG}" \
    --set admin.deployment.image.tag="${ADMIN_IMAGE_TAG}" \
    --set monitoring.slack_api_url="${SLACK_WEB_HOOK}"
    