apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus
  name: {{ template "shift-scheduler.name" . }}
spec:
{{- $files := .Files }}
{{- range $path, $bytes := .Files.Glob "prometheus-rules/*.yaml" }}
{{ $files.Get $path | indent 2 }}
{{- end }}