apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: alertmanager-kube-prometheus
type: Opaque
data:
  alertmanager.yaml: {{ include "alerts.config.yaml.tpl" . | b64enc }}
{{ (.Files.Glob "am-notification-templates/*.tmpl").AsSecrets | indent 2 }}