# Default values for installation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 2
  image:
    repository: iluvzhouying/shift-scheduler-api
  serverPort: 80

service:
  type: ClusterIP
  port: 80
