#!/bin/bash

set -euxo pipefail

# decrypt service account file
openssl aes-256-cbc -K $encrypted_447b2a4925b5_key -iv $encrypted_447b2a4925b5_iv -in travis-ci-srv-account.json.enc -out travis-ci-srv-account.json -d

# install gcloud
curl -o /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz
tar -xzf /tmp/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz -C /tmp/
/tmp/google-cloud-sdk/install.sh -q

# install helm
curl -o /tmp/helm-v2.9.1-linux-amd64.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz
tar -xzf /tmp/helm-v2.9.1-linux-amd64.tar.gz -C /tmp/
sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm