global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'null'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'null'
receivers:
- name: 'slack'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#alerts'